[workspace]
name = "vrp-tfm"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.10.*"
numpy = "*"
pandas = ">=2.3.3,<3"
sqlalchemy = ">=2.0.46,<3"
pyyaml = ">=6.0.3,<7"
oracledb = ">=3.4.2,<4"

[pypi-dependencies]
ortools = "*"


